name: docker-push
on:
  push:
    branches: [ dev ]

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mmateus1/test-deployment
          tags: latest
          path: metric-platform/
          
