- name: Docker Build & Push
  uses: mr-smithers-excellent/docker-build-push@v2
  with:
    # Name of the Docker image
    image: 
    # Tag override for Docker image
    tag: # optional
    # Target Docker registry
    registry: 
    # Location of Dockerfile, if not Dockerfile in root directory
    dockerfile: # optional, default is Dockerfile
    # Docker build arguments in format KEY=VALUE,KEY=VALUE
    buildArgs: # optional
    # Docker registry username
    username: # optional
    # Docker registry password
    password: # optional



name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - working-directory: metric-platform
    - name: Build the Docker image
    - run: docker build . --file Dockerfile --tag oss-app-metric-plat:$(date +%s)
